const cardsFromBRO = [
  {
    id: 9094001,
    symbol: "⚙️",
    set: "BRO",
    name: "Disenchant",
    color: "white",
    cost: "1W",
    type: "Instant",
    text: "Sacrifice a random artifact or enchantment you control. If you can't, another eligible player must if able, and each player who doesn't gains a Woe counter.",
    revealed: true,
  },
  {
    id: 9094002,
    symbol: "⚙️",
    set: "BRO",
    name: "Loran's Escape",
    color: "white",
    cost: "W",
    type: "Instant",
    text: "Put a shield counter on a random target foe. If you can't, instead put a shield counter on a random eligible player's random foe and you gain a Woe counter.",
    revealed: true,
  },
  {
    id: 9094003,
    symbol: "⚙️",
    set: "BRO",
    name: "Calamity's Wake",
    color: "white",
    cost: "1W",
    type: "Instant",
    text: "Exile all graveyards. Players can't cast noncreature spells this turn. Gain a Woe counter. Exile Calmity's Wake.",
    revealed: true,
  },
  {
    id: 9094004,
    symbol: "⚙️",
    set: "BRO",
    name: "Defabricate",
    color: "blue",
    cost: "1U",
    type: "Instant",
    text: "Mute target attacking creature unless you mute a nontoken artifact you control.",
    revealed: true,
  },
  {
    id: 9094005,
    symbol: "⚙️",
    set: "BRO",
    name: "Flow of Woe",
    color: "blue",
    cost: "4U",
    type: "Instant",
    text: "For each attacking creature you control, give a Woe counter to one of your teammates.",
    revealed: true,
  },
  {
    id: 9094006,
    symbol: "⚙️",
    set: "BRO",
    name: "Urza's Rebuff",
    color: "blue",
    cost: "1UU",
    type: "Instant",
    text: "Choose one -- put a stun counter on two tapped permanents you control, or return a land you control to its owner's hand.",
    revealed: true,
  },
  {
    id: 9094007,
    symbol: "⚙️",
    set: "BRO",
    name: "Go for the Throat",
    color: "black",
    cost: "1B",
    type: "Instant",
    text: "If target attacking creature is an artifact, you gain a Weal counter. Otherwise, sacrifice that creature.",
    revealed: true,
  },
  {
    id: 9094008,
    symbol: "⚙️",
    set: "BRO",
    name: "Overwhelming Remorse",
    color: "black",
    cost: "1B",
    type: "Instant",
    text: "If you control a planeswalker, exile a random planeswalker you control. Otherwise, exile target attacking creature.",
    revealed: true,
  },
  {
    id: 9094009,
    symbol: "⚙️",
    set: "BRO",
    name: "Disfigure",
    color: "black",
    cost: "B",
    type: "Instant",
    text: "Target attacking creature gets -2/-2 until end of turn.",
    revealed: true,
  },
  {
    id: 9094010,
    symbol: "⚙️",
    set: "BRO",
    name: "Unleash Shell",
    color: "red",
    cost: "3RR",
    type: "Instant",
    text: `This spell deals 5 damage to target attacking creature. If you control a planeswalker, this deals 2 damage to a random planeswalker you control, otherwise it deals 2 damage to you.`,
    revealed: true,
  },
  {
    id: 9094011,
    symbol: "⚙️",
    set: "BRO",
    name: "Mishra's Onslaught",
    color: "red",
    cost: "3R",
    type: "Instant",
    text: "Encounter two 1/1 colorless Soldier artifact creature tokens. They block target attacking creature this turn if able. Tap them at the end of combat if they survive.",
    revealed: true,
  },
  {
    id: 9094012,
    symbol: "⚙️",
    set: "BRO",
    name: "Whirling Strike",
    color: "red",
    cost: "1R",
    type: "Instant",
    text: "Starting with you, each player must choose a random foe (they're facing if able) and give it an unused counter from the following list: first strike, trample, and +1/+1. Then choose one of those creatures randomly and untap it. It blocks target attacking creature this turn if able. Tap it at the end of combat.",
    revealed: true,
  },
  {
    id: 9094013,
    symbol: "⚙️",
    set: "BRO",
    name: "Giant Growth",
    color: "green",
    cost: "G",
    type: "Instant",
    text: "Choose a random foe you're facing if able and untap it, or else encounter a 1/1 colorless Soldier artifact creature token. That creature gets +3/+3 until end of turn and blocks target attacking creature if able. Tap it at the end of combat.",
    revealed: true,
  },
  {
    id: 9094014,
    symbol: "⚙️",
    set: "BRO",
    name: "Fog of War",
    color: "green",
    cost: "G",
    type: "Instant",
    text: "Prevent all combat damage that would be dealt by target attacking creature this turn. Put a stun counter on it.",
    revealed: true,
  },
  {
    id: 9094015,
    symbol: "⚙️",
    set: "BRO",
    name: "Wasteful Harvest",
    color: "green",
    cost: "G",
    type: "Instant",
    text: "Mill five cards. For each creature card you milled in this way, you gain a Woe counter.",
    revealed: true,
  },
];

export default cardsFromBRO;
