const makeBlankInstantCards = () => {
  let blankInstantCards = [];
  for (let x = 0; x < 48; x++) {
    const blankCard = {
      id: 9999999 - x,
      symbol: "🌎",
      set: "core",
      name: "All Clear",
      color: "colorless",
      cost: "0",
      type: "Instant",
      text: "No trick.",
      revealed: true,
      included: true,
      overrideDescription: null,
    };
    blankInstantCards.push(blankCard);
  }
  return blankInstantCards;
};

const blankInstants = makeBlankInstantCards();

const coreInstants = [
  ...blankInstants,
  {
    id: 9999001,
    symbol: "🌎",
    set: "core",
    color: "white",
    collector_number: "001",
    name: "Untimely Ascension",
    cost: "4W",
    type: "Instant",
    text: "Exile target creature.",
    revealed: true,
    included: true,
    overrideDescription: null,
  },
  {
    id: 9999002,
    symbol: "🌎",
    set: "core",
    color: "white",
    collector_number: "002",
    name: "Sense of Contentment",
    cost: "1WW",
    type: "Instant",
    text: "Remove target attacking creature from combat, then encounter a 'Pacified' enchantment aura token attached to that creature with flash and 'I can't attack or block.'",
    revealed: true,
    included: true,
    overrideDescription: null,
  },
  {
    id: 9999003,
    symbol: "🌎",
    set: "core",
    color: "white",
    collector_number: "003",
    name: "Spell of Silence",
    cost: "1W",
    type: "Instant",
    text: "Mute target creature. (It loses all rules text and can't have or gain rules text. It's a vanilla creature.)",
    revealed: true,
    included: true,
    overrideDescription: null,
  },
  {
    id: 9999004,
    symbol: "🌎",
    set: "core",
    color: "blue",
    collector_number: "004",
    name: "Aether Cyclone",
    cost: "1U",
    type: "Instant",
    text: "Return target creature to its owner's hand. If a player controls seven or more mana permanents as this spell is cast, instead return ALL nonland permanents in play to their owner's hands.",
    revealed: true,
    included: true,
    overrideDescription: null,
  },
  {
    id: 9999005,
    symbol: "🌎",
    set: "core",
    color: "blue",
    collector_number: "005",
    name: "Force Harmonics",
    cost: "UU",
    type: "Instant",
    text: "You get a number of Woe counters equal to target creature's mana value. If that creature is a token, instead you get three Woe counters.",
    revealed: true,
    included: true,
    overrideDescription: null,
  },
  {
    id: 9999006,
    symbol: "🌎",
    set: "core",
    color: "blue",
    collector_number: "006",
    name: "Icy Reprisal",
    cost: "1UU",
    type: "Instant",
    text: "The next time target creature deals combat damage this turn, tap it and put that many stun counters on it.",
    revealed: true,
    included: true,
    overrideDescription: null,
  },
  {
    id: 9999007,
    symbol: "🌎",
    set: "core",
    color: "black",
    collector_number: "007",
    name: "Death Spell",
    cost: "1BB",
    type: "Instant",
    text: "Destroy target creature.",
    revealed: true,
    included: true,
    overrideDescription: null,
  },
  {
    id: 9999008,
    symbol: "🌎",
    set: "core",
    color: "black",
    collector_number: "008",
    name: "Vile Residue",
    cost: "XB",
    type: "Instant",
    text: "Target creature gets -X/-X until end of turn, where X is the number of tapped mana permanents you control as this spell is cast.",
    revealed: true,
    included: true,
    overrideDescription: null,
  },
  {
    id: 9999009,
    symbol: "🌎",
    set: "core",
    color: "black",
    collector_number: "009",
    name: "Oozing Wound",
    cost: "2BB",
    type: "Instant",
    text: "Encounter a 'Bleeding' enchantment aura token attached to target attacking creature with flash and 'At the beginning of your upkeep, you lose 1 life.'",
    revealed: true,
    included: true,
    overrideDescription: null,
  },
  {
    id: 9999010,
    symbol: "🌎",
    set: "core",
    color: "red",
    collector_number: "010",
    name: "Hostile Terrain",
    cost: "XR",
    type: "Instant",
    text: "Deal X damage to target creature, where X is the number of untapped mana permanents you control as this spell is cast.",
    revealed: true,
    included: true,
    overrideDescription: null,
  },
  {
    id: 9999010,
    symbol: "🌎",
    set: "core",
    color: "red",
    collector_number: "010",
    name: "Hostile Terrain",
    cost: "XR",
    type: "Instant",
    text: "Deal X damage to target creature, where X is the number of untapped mana permanents you control as this spell is cast.",
    revealed: true,
    included: true,
    overrideDescription: null,
  },
  {
    id: 9999011,
    symbol: "🌎",
    set: "core",
    color: "red",
    collector_number: "011",
    name: "Sticks and Stones",
    cost: "1R",
    type: "Instant",
    text: "Encounter an 'Enraged' enchantment token attached to a random (untapped) creature you control with the highest rarity with flash and 'I must attack the Nexus with the highest life total each combat if able.'",
    revealed: true,
    included: true,
    overrideDescription: null,
  },
  {
    id: 9999012,
    symbol: "🌎",
    set: "core",
    color: "red",
    collector_number: "012",
    name: "Wrack and Ruin",
    cost: "1RR",
    type: "Instant",
    text: "The next time target creature deals combat damage this turn, distribute that many blight counters among (unblighted) lands you control.",
    revealed: true,
    included: true,
    overrideDescription: null,
  },
  {
    id: 9999013,
    symbol: "🌎",
    set: "core",
    color: "green",
    collector_number: "013",
    name: "Feral Ambush",
    cost: "3G",
    type: "Instant",
    text: "The largest foe in play strikes target creature. If there are no foes in play as this spell resolves, first encounter a tapped 4/4 green Beast creature token.",
    revealed: true,
    included: true,
    overrideDescription: null,
  },
  {
    id: 9999014,
    symbol: "🌎",
    set: "core",
    color: "green",
    collector_number: "014",
    name: "Demoralize",
    cost: "1G",
    type: "Instant",
    text: "Sacrifice a random (nontoken) artifact or enchantment you control with the highest rarity.",
    revealed: true,
    included: true,
    overrideDescription: null,
  },
  {
    id: 9999015,
    symbol: "🌎",
    set: "core",
    color: "green",
    collector_number: "015",
    name: "Defang",
    cost: "1GG",
    type: "Instant",
    text: "Encounter a 'Defanged' enchantment aura token attached to target attacking creature with flash and 'Prevent all combat damage that would be dealt by enchanted creature.'",
    revealed: true,
    included: true,
    overrideDescription: null,
  },
];

module.exports = coreInstants;
