const playerData = [
  {
    id: 1,
    name: "Timmy",
    commander: "Animar",
    commanderB: "",
    faction: "red",
    resources: {
      life: 20,
      woe: 0,
      weal: 0,
      poison: 0,
      energy: 0,
      xp: 0,
      taxA: 0,
      taxB: 0,
    },
  },
  {
    id: 2,
    name: "Johnny",
    commander: "Huatli, Radiant Champion",
    commanderB: "Travel Preparations",
    faction: "white",
    resources: {
      life: 20,
      woe: 0,
      weal: 0,
      poison: 0,
      energy: 0,
      xp: 0,
      taxA: 0,
      taxB: 0,
    },
  },
  {
    id: 3,
    name: "Spike",
    commander: "Florian Voldaren",
    commanderB: "",
    faction: "blue",
    resources: {
      life: 20,
      woe: 0,
      weal: 0,
      poison: 0,
      energy: 0,
      xp: 0,
      taxA: 0,
      taxB: 0,
    },
  },
];

export default playerData;
