const playerData = [
  {
    id: 1,
    name: "Bartholomew",
    commander: "Kiora, Capsizer of Ships",
    commanderB: "Rampant Growth",
    faction: "blue",
    resources: {
      life: 2,
      woe: 0,
      weal: 0,
      poison: 0,
      energy: 0,
      xp: 0,
      taxA: 0,
      taxB: 0,
    },
  },
  {
    id: 2,
    name: "Alexandria",
    commander: "Huatli, Radiant Champion",
    commanderB: "Travel Preparations",
    faction: "white",
    resources: {
      life: 2,
      woe: 0,
      weal: 0,
      poison: 0,
      energy: 0,
      xp: 0,
      taxA: 0,
      taxB: 0,
    },
  },
  {
    id: 3,
    name: "Sebastian",
    commander: "Florian Voldaren",
    commanderB: null,
    faction: "red",
    resources: {
      life: 2,
      woe: 0,
      weal: 0,
      poison: 0,
      energy: 0,
      xp: 0,
      taxA: 0,
      taxB: 0,
    },
  },
];

export default playerData;
