const therosCards = [
  {
    id: 9001001,
    symbol: "☀️",
    set: "core",
    name: "ALL CLEAR",
    color: "colorless",
    cost: "W",
    type: "Instant",
    text: "No effect.",
    revealed: true,
  },
  {
    id: 1001001,
    symbol: "☀️",
    name: "Heliod's Power",
    color: "white",
    cost: "W",
    type: "Sorcery",
    text: "Exile target attacking creature. You may search your library for a basic land and put into play tapped. If you do, shuffle your library.",
    revealed: true,
  },
  {
    id: 1001002,
    symbol: "☀️",
    name: "Wrath of the Sun God",
    color: "white",
    cost: "W",
    type: "Sorcery",
    revealed: true,
  },
  {
    id: 1001003,
    symbol: "☀️",
    name: "Acolyte of the Sun",
    color: "white",
    cost: "WW",
    type: "Creature - Summon",
    text: "Encounter a 1/2 white Cleric creature token with lifelink and protector.",
    revealed: true,
  },
  {
    id: 1001004,
    symbol: "☀️",
    name: "SPELL 1",
    color: "red",
    cost: "R",
    type: "Instant",
    text: "Encounter a 1/2 white Cleric creature token with lifelink and protector.",
    revealed: true,
  },
  {
    id: 1002001,
    symbol: "🌊",
    name: "Thassa's Disregard",
    color: "blue",
    cost: "W",
    type: "Sorcery",
    text: "Exile target attacking creature. You may search your library for a basic land and put into play tapped. If you do, shuffle your library.",
    revealed: true,
  },
  {
    id: 1002002,
    symbol: "🌊",
    name: "Tidal Wave",
    color: "blue",
    cost: "W",
    type: "Sorcery",
    revealed: true,
  },
  {
    id: 1002003,
    symbol: "🌊",
    name: "Dakra Isles Invasion",
    color: "blue",
    cost: "W",
    type: "Battle - Siege",
    text: "Put an 'Invasion of Dakra Isles' battle token into play under your protection.",
    revealed: true,
  },
  {
    id: 1002004,
    symbol: "☀️",
    name: "It's number 2!",
    color: "red",
    cost: "R",
    type: "Instant",
    text: "Encounter a 1/2 white Cleric creature token with lifelink and protector.",
    revealed: true,
  },
  {
    id: 1003001,
    symbol: "☠️",
    name: "Erebos's Death Face",
    color: "black",
    cost: "W",
    type: "Socery",
    text: "Exile target attacking creature. You may search your library for a basic land and put into play tapped. If you do, shuffle your library.",
    revealed: true,
  },
  {
    id: 1003002,
    symbol: "☠️",
    name: "Zombie Rave",
    color: "black",
    cost: "W",
    type: "Sorcery",
    revealed: true,
  },
  {
    id: 1003004,
    symbol: "☀️",
    name: "Three is Great",
    color: "red",
    cost: "R",
    type: "Instant",
    text: "Encounter a 1/2 white Cleric creature token with lifelink and protector.",
    revealed: true,
  },
  {
    id: 1004001,
    symbol: "⚒️",
    name: "Purphoros Gets Noticed",
    color: "white",
    cost: "W",
    type: "Sorcery",
    text: "Exile target attacking creature. You may search your library for a basic land and put into play tapped. If you do, shuffle your library.",
    revealed: true,
  },
  {
    id: 1004002,
    symbol: "⚒️",
    name: "Hammer Down",
    color: "white",
    cost: "W",
    type: "Sorcery",
    revealed: true,
  },
  {
    id: 1004003,
    symbol: "⚒️",
    name: "Ashsmoke Forge",
    color: "colorless",
    cost: "4",
    type: "Artifact",
    text: "You gain an emblem with: 'At the beginning of your upkeep, roll a d6 and add the number of rares you control. If the result is 4 or greater, encounter a 2/1 Bronze Sable artifact creature token.'",
    revealed: true,
  },
  {
    id: 1004004,
    symbol: "☀️",
    name: "Chimes of Arousal",
    color: "red",
    cost: "R",
    type: "Instant",
    text: "Encounter a 1/2 white Cleric creature token with lifelink and protector.",
    revealed: true,
  },
  {
    id: 1005001,
    symbol: "🏹",
    name: "Nylea's Boon",
    color: "green",
    cost: "W",
    type: "Sorcery",
    text: "Exile target attacking creature. You may search your library for a basic land and put into play tapped. If you do, shuffle your library.",
    revealed: true,
  },
  {
    id: 1005002,
    symbol: "🏹",
    name: "Resonant Bowstring",
    color: "green",
    cost: "W",
    type: "Sorcery",
    revealed: true,
  },
  {
    id: 1005004,
    symbol: "☀️",
    name: "Let Me Sleep In",
    color: "red",
    cost: "R",
    type: "Instant",
    text: "Encounter a 1/2 white Cleric creature token with lifelink and protector.",
    revealed: true,
  },
];
export default therosCards;
